url: "https://stoppingagents.com"
name: Stopping Agents
description: Stopping Agents
author_image_path: /images/logo.png

# Markdown rendering
kramdown:
  input: GFM
  #  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

highlighter: rouge

# Site settings
permalink: /blog/:year/:month/:day/:title/

# important since the site is compiled
# on Github's servers
timezone: America/New_York

plugins:
  - jekyll-redirect-from
